# Generated by Django 4.2 on 2023-04-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
